In [ ]:
#.1 python --version
#2. pip -- version
#3. jupyter -- version

In [2]:
#problem is 
[1,2,3]

[1, 2, 3]

In [3]:
## but 
[1,2,3]*2 #--> This is the problem and python is dymaic type language and C is statically type language, So numpy works dirctly with c making it faster

[1, 2, 3, 1, 2, 3]

In [2]:
# ! pip install numpy
import numpy as np #alias

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [11]:
a = np.arange(1,5,0.5) # we can give step size as float also
a  # these are not python arrays, they are C arrays

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [14]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [3]:
c = np.arange(12)
c # we can also pass tuples

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 1 dimension --> vector
# 2 dimension --> matrix
# 3 dimension -- tensor

In [18]:
c.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
c.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
a = np.array([-1,0,1.5,100])
a #When we make 1 element float, it makes all of them as float. As we are working with C

array([ -1. ,   0. ,   1.5, 100. ])

In [24]:
a = np.array([-1,0,1,100],dtype='int8')  # 8 means 8 bit --> 2**8 --> and we can select between -127 to 128
a*2

array([ -2,   0,   2, -56], dtype=int8)

In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
a[0]

0

In [27]:
a[-1]

11

In [28]:
a[1:7]

array([1, 2, 3, 4, 5, 6])

In [29]:
a[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [30]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

In [32]:
a[0] =100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [33]:
## Insert and remove is  not allowed as length is fixed in C. We can only upate the value

a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a[1:3,2:]

array([[ 6,  7],
       [10, 11]])

In [37]:
a[1:3,-1]  # They came horizontally

array([ 7, 11])

In [38]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

### How to create tensor

In [39]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
c[1,1,1]

17

In [41]:
c[1,:,:] # or c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Vectorization

In [43]:
a = np.arange(12)
a # vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
b = a.reshape(3,4)
b #matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a *2 # This is called Vectorization as the operation is applied on each element. Also, Numpy is called as vectorized library

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [46]:
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [47]:
b+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [48]:
b**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [ ]:
## Vectorization <==> Broadcasting <==> Mapping

In [49]:
a>6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True])

In [51]:
a = np.arange(12)
b = np.arange(12)

In [52]:
a*b   # Normal multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [53]:
a.reshape(3,4) * b.reshape(3,4)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [54]:
a.dot(b)

506

In [56]:
a.shape # 1 dimension -- this is a vector

(12,)

In [57]:
a.reshape(1,12) # 2 dimension --> this is a matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [59]:
A = a.reshape(1,12)
A.shape # 2 dimension

(1, 12)

In [60]:
B = b.reshape(1,12)
B.shape

(1, 12)

In [62]:
B.T

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [63]:
A.dot(B.T)

array([[506]])

In [66]:
B.T.dot(A)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121]])

## Masking

In [67]:
a = np.arange(30)

In [68]:
a>15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [69]:
a[a>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [70]:
a = a.reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [71]:
a[a>15] ## So, we will get an Vector

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
a[a>15].reshape(7,2)

array([[16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [73]:
a = np.arange(12)
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [74]:
b = a.reshape(3,4)
b.flags # we can see that OWNDATA = FALSE, as we have not created this data and b is only using this data

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [75]:
c = a[:5]
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [77]:
a[0]=100
a # changing the value if a[0]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [78]:
b # b value also changes

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [79]:
c # c value also changess

array([100,   1,   2,   3,   4])

In [81]:
d = a[a>5]
d.flags # Hre OWNDATA IS true as the new data is created from MASKING

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [82]:
a = np.arange(12).reshape(3,4)
a # Convert this matrix to vector

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a.reshape(12) # Coverted to vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a.flatten() # Converted to vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
a.reshape(6,-1) ## Numpy will itself figureout what should come in place of -1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [88]:
a.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [89]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Special Arrays

In [6]:
np.zeros((3,4) )# When we do shift+tab, we can see that we have to pass shape and to pass we have to pass tuple, ow 4 will do to other place

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.ones((4,3)) *5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [94]:
np.empty((4,5)) ## garbage values--> it doesnot set the value,rather the values that were present in heap will be printed.

array([[2.92876767e-312, 0.00000000e+000, 1.41537862e+161,
        5.22182633e+180, 7.33952596e+223],
       [4.83245960e+276, 6.98345625e-077, 6.98345624e-077,
        6.01391519e-154, 7.06673073e-096],
       [7.06652016e-096, 1.81148490e-152, 9.37041222e-076,
        6.98345624e-077, 1.95360427e-109],
       [2.86752281e+161, 2.78225500e+296, 9.80058441e+252,
        1.23971686e+224, 2.05697313e-307]])

In [95]:
# empty has not set anything or any value, wgere as in case of np.zeros we have put 0 to every value. So it saves a lot of time
#using empty value

In [96]:
np.identity(3) #always square

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.eye(3,4) # can be rectangular

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [101]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

## ANALYSIS

In [103]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
np.max(a)

11

In [105]:
np.max(b)

11

In [106]:
np.max(b,axis=0) #merge the rows, but answer will be column wise

array([ 8,  9, 10, 11])

In [108]:
np.max(b,axis=1) #merge columns

array([ 3,  7, 11])

In [109]:
np.sum(a)

66

In [110]:
np.sum(b,axis=0)

array([12, 15, 18, 21])

In [111]:
np.sum(b,axis=1)

array([ 6, 22, 38])

In [113]:
np.mean(b,axis=0)

array([4., 5., 6., 7.])

In [117]:
np.median(b)

5.5

In [118]:
np.std(a)

3.452052529534663

In [119]:
np.std(b,axis=0) # Standard deviation shows or tells us how much the data is spreaded

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [120]:
np.std(b,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

## Distribution and Random

In [121]:
np.random.rand(5)

array([0.01803959, 0.42117322, 0.6722292 , 0.66930497, 0.26222274])

In [7]:
np.random.rand(4,3)  ## No need to gave shape as tuple as we can see from shift+tab

array([[0.84645946, 0.58829485, 0.93801242],
       [0.89799635, 0.37172243, 0.20634623],
       [0.36646334, 0.07750119, 0.70872268],
       [0.10071626, 0.36546504, 0.89436397]])

In [125]:
np.random.randn(4,3)*10

array([[ 19.09814167,  21.81700224,   0.158069  ],
       [ 20.79863525,   5.02267606,  -7.13444765],
       [  0.5493815 ,  23.09636422,   5.80132553],
       [ -6.5751871 ,  -7.9254312 , -19.54063791]])

In [127]:
# we want nu,bers that are betwen 90-100

s = 90 + np.random.randn(4,3)*10
s.astype('int8')

array([[92, 78, 85],
       [99, 88, 84],
       [82, 83, 75],
       [96, 83, 82]], dtype=int8)

In [19]:
import time

ticks = time.time()
ticks  # since 1 jan 1970 # EPOCH TIME

1559849097.5698495

In [ ]:
# 1. Easily manipulate
#2. Time zone indepdendent --> 

# we always get the different random numbers evrytime as input is time in random function code. we call it as SEED.But if we set SEED,the input and output doesnot change

In [27]:
np.random.seed(100)
print(np.random.randn(1))
print(np.random.randn(1))
print(np.random.randn(1))

[-1.74976547]
[0.3426804]
[1.1530358]


In [21]:
# we use seed to keep the variation less.

In [145]:
np.random.randint(50,60,5)

array([57, 51, 51, 57, 57])

In [146]:
#random.randn --> takes between 0 and 1 --> uniform distribution

In [155]:
mu = 100
sigma=15
s = np.random.normal(mu,sigma,1000) # majority numbers are around 100 # Bur when we increase it to 1000, we can see that noide will be less and mu and sigma will get more accurate

In [156]:
s.mean()

99.73296526395671

In [157]:
s.std()

15.00294741658377